language: ruby
rvm:
  - "2.3.0"
before_script:
- bundle install --path vendor/bundle
- bundle exec rake db:create
- bundle exec rake db:migrate

script:
- bundle exec cucumber
- bundle exec rspec


deploy:
  provider: heroku
  api_key:
    secure: c2471f4b-ebb1-41a5-b8d5-487f86458829

  app: travisrails

  on:
    all_branches: true

deploy:
  provider: heroku
  api_key:
    secure: ${API_KEY}



  run:
    - "rake heroku:secrets RAILS_ENV=production"
    - "rake db:drop"
    - "rake db:create"
    - "rake db:migrate"
    - "rake db:seed"
    - "rake assets:precompile"
